### ISSUE TITLE
Some methods are hidden for Objective-C

### ISSUE THREAD

**Issue by alexruperez** [gapl/PushReview#2]
Some methods like scheduleReviewNotification and usesBeforePresenting are hidden when using PushReview with Objective-C and CocoaPods. Because NSTimeInterval? and Int? optionals can't work with Objective-C.

**Comment by gapl** [comment]
Nice catch, thank you for bringing this to my attention! Will fix :)

**Comment by gapl** [comment]
Closing this - fixed in the new release v0.2.3.
